import Foundation

extension HandbookContent {
    /// Glossary entry: short definition plus optional "in practice" note.
    private static func term(_ id: String, _ ru: String, _ en: String, _ defRu: String, _ defEn: String,
                             practice: LText? = nil, tags: [String] = []) -> HandbookArticle {
        var blocks: [HandbookBlock] = [.paragraph(LText(defRu, defEn))]
        if let practice { blocks.append(.tip(practice)) }
        return HandbookArticle("term." + id, .glossary, title: LText(ru, en), subtitle: LText(en, ru), tags: tags, blocks: blocks)
    }

    static let glossary: [HandbookArticle] = [
        term("gain", "Гейн (Trim)", "Gain (trim)", "Усиление предусилителя на входе канала — первый и главный регулятор уровня.",
             "Preamp amplification at the channel input — the first and main level control.", practice: LText("См. «Гейн-стейджинг».", "See Gain staging.")),
        term("headroom", "Запас по уровню", "Headroom", "Разница между рабочим уровнем и уровнем перегрузки, дБ.",
             "Difference between the operating level and clipping, dB."),
        term("clip", "Клиппинг", "Clipping", "Срез вершин сигнала при превышении максимального уровня — слышен как треск и жёсткость.",
             "Flattening of signal peaks above the maximum level — heard as crackle and harshness."),
        term("dbfs", "dBFS", "dBFS", "Децибелы относительно полной шкалы цифровой системы; 0 dBFS — максимум.",
             "Decibels relative to digital full scale; 0 dBFS is the maximum."),
        term("dbu", "dBu", "dBu", "Уровень напряжения относительно 0,775 В. Профессиональная линия — +4 dBu.",
             "Voltage level relative to 0.775 V. Pro line level is +4 dBu.", tags: ["уровень", "line"]),
        term("dbspl", "dB SPL", "dB SPL", "Звуковое давление относительно порога слышимости 20 мкПа.",
             "Sound pressure relative to the 20 µPa threshold of hearing.", tags: ["громкость", "звуковое давление"]),
        term("dba", "Взвешивание A и C", "A and C weighting", "Частотные фильтры шумомера: A — как ухо на тихих уровнях (без низа), C — почти ровно, учитывает бас.",
             "Sound level meter filters: A follows the ear at low levels (little bass), C is nearly flat and includes bass.", tags: ["dba", "dbc", "leq"]),
        term("phantom", "Фантомное питание +48 В", "Phantom power +48 V", "Постоянное напряжение по контактам 2 и 3 XLR для конденсаторных микрофонов и активных DI.",
             "DC on XLR pins 2 and 3 powering condenser mics and active DIs.",
             practice: LText("Включайте и выключайте при опущенном фейдере. Ленточным микрофонам старого типа может навредить неисправный кабель с фантомом.",
                             "Switch it with the fader down. Faulty cables with phantom can harm vintage ribbon mics."), tags: ["48v", "фантом"]),
        term("balanced", "Симметричная линия", "Balanced line", "Два провода с противофазным сигналом и экран; помехи вычитаются на входе.",
             "Two conductors carrying opposite signals plus a shield; interference cancels at the input.", tags: ["xlr", "trs"]),
        term("impedance", "Импеданс", "Impedance", "Полное сопротивление переменному току, Ом. У колонок — номинал 4, 8, 16 Ом.",
             "AC resistance in ohms. Loudspeakers are rated 4, 8 or 16 Ω.", tags: ["ом", "ohm"]),
        term("hpf", "ФВЧ (обрезной фильтр)", "High-pass filter (HPF)", "Фильтр, убирающий частоты ниже заданной; на вокале обычно 80–120 Гц.",
             "Removes frequencies below the cutoff; on vocals usually 80–120 Hz.", tags: ["low cut", "lowcut", "срез"]),
        term("lpf", "ФНЧ", "Low-pass filter (LPF)", "Фильтр, убирающий частоты выше заданной; например, для сабвуфера.",
             "Removes frequencies above the cutoff; e.g. for a subwoofer.", tags: ["high cut"]),
        term("peq", "Параметрический эквалайзер", "Parametric EQ", "Полосы с регулировкой частоты, усиления и добротности (Q).",
             "Bands with adjustable frequency, gain and bandwidth (Q).", tags: ["eq", "эквалайзер"]),
        term("geq", "Графический эквалайзер", "Graphic EQ", "Набор фиксированных полос (обычно 31 по 1/3 октавы) — для мониторов и порталов.",
             "Fixed bands (usually 31 at 1/3 octave) — for wedges and mains.", tags: ["31 band", "eq"]),
        term("q", "Добротность (Q)", "Q (bandwidth)", "Ширина полосы эквалайзера: чем больше Q, тем уже полоса.",
             "EQ band width: higher Q means narrower.", tags: ["bandwidth", "полоса"]),
        term("compressor", "Компрессор", "Compressor", "Уменьшает усиление, когда сигнал выше порога, на величину, заданную ratio.",
             "Reduces gain above the threshold by the ratio.", practice: LText("См. «Компрессор: стартовые настройки».", "See Compressor: starting points.")),
        term("limiter", "Лимитер", "Limiter", "Компрессор с очень большим ratio — не даёт сигналу превысить порог.",
             "A compressor with a very high ratio — keeps the signal below the threshold."),
        term("gate", "Гейт", "Gate", "Закрывает канал, пока сигнал ниже порога — убирает наводки соседних инструментов.",
             "Mutes the channel while the signal is below the threshold — removes spill."),
        term("expander", "Экспандер", "Expander", "Мягкий гейт: тихие сигналы ослабляются, а не обрезаются полностью.",
             "A soft gate: quiet signals are reduced, not cut off."),
        term("deesser", "Де-эссер", "De-esser", "Компрессор, реагирующий на свистящие «с», «ш» (5–9 кГц).",
             "A compressor that reacts to sibilance (5–9 kHz)."),
        term("aux", "Aux / посыл", "Aux send", "Отдельная смесь каналов для мониторов или эффектов.",
             "A separate mix of channels for monitors or effects.", tags: ["send", "мониторный микс", "bus"]),
        term("prepost", "Pre / Post fader", "Pre / post fader", "Посыл до фейдера канала (мониторы — не зависят от FOH-фейдера) или после (эффекты — следуют за фейдером).",
             "Send before the channel fader (monitors, independent of FOH fader) or after it (effects, follow the fader)."),
        term("dca", "DCA / VCA", "DCA / VCA", "Фейдер, управляющий уровнем группы каналов без суммирования звука.",
             "A fader controlling a group of channels' levels without summing audio.", tags: ["vca", "группа"]),
        term("subgroup", "Подгруппа", "Subgroup", "Шина, в которой каналы суммируются; на неё можно повесить обработку.",
             "A bus where channels are summed; it can carry processing."),
        term("matrix", "Матрица", "Matrix", "Выходы, собираемые из шин (L/R, групп) — для дилеев, записи, трансляции.",
             "Outputs mixed from buses (L/R, groups) — for delays, recording, broadcast."),
        term("pfl", "PFL / AFL / Solo", "PFL / AFL / Solo", "Прослушивание канала в наушниках: до фейдера (PFL) или после (AFL).",
             "Listening to a channel in headphones: before the fader (PFL) or after it (AFL).", tags: ["solo", "соло", "cue"]),
        term("talkback", "Толкбэк", "Talkback", "Микрофон звукорежиссёра для разговора со сценой через мониторы.",
             "The engineer's microphone to talk to the stage via monitors."),
        term("scene", "Сцена / снапшот", "Scene / snapshot", "Сохранённое состояние пульта, загружаемое по песне или номеру.",
             "A stored console state recalled per song or cue.", tags: ["snapshot", "preset"]),
        term("recallSafe", "Recall Safe", "Recall safe", "Параметры, которые не меняются при загрузке сцены.",
             "Parameters that stay put when a scene is recalled.", tags: ["safe", "scope"]),
        term("stagebox", "Стейджбокс", "Stage box", "Входы-выходы на сцене, соединённые с пультом цифровой линией (AES50, Dante, MADI…).",
             "Inputs and outputs on stage linked to the console by a digital link (AES50, Dante, MADI…).", tags: ["dl16", "s16", "rio"]),
        term("splitter", "Сплиттер", "Splitter", "Разделение сигнала микрофона на несколько пультов (FOH, мониторы, запись).",
             "Splitting mic signals to several consoles (FOH, monitors, recording)."),
        term("aes50", "AES50", "AES50", "Цифровая линия по витой паре: 48 каналов в каждую сторону при 48 кГц (Behringer / Midas).",
             "Digital link over Cat5: 48 channels each way at 48 kHz (Behringer / Midas)."),
        term("dante", "Dante", "Dante", "Сетевой аудиопротокол поверх обычного Ethernet; маршрутизация в Dante Controller.",
             "Network audio over standard Ethernet; routed in Dante Controller."),
        term("madi", "MADI", "MADI", "До 64 каналов по одному коаксиалу или оптике.", "Up to 64 channels over one coax or fibre."),
        term("wordclock", "Word clock", "Word clock", "Сигнал синхронизации цифровых устройств; в системе один ведущий (master).",
             "Clock signal for digital devices; one master per system.", tags: ["sync", "синхронизация"]),
        term("latency", "Латентность", "Latency", "Задержка сигнала при обработке и передаче; критична для ушных мониторов.",
             "Signal delay from processing and transport; critical for in-ears.", tags: ["задержка"]),
        term("feedback", "Заводка (обратная связь)", "Feedback", "Самовозбуждение: микрофон слышит колонку, сигнал зацикливается на одной частоте.",
             "Self-oscillation: the mic hears the speaker and the signal loops at one frequency.", practice: LText("См. «Прозвонка мониторов».", "See Ringing out monitors.")),
        term("pattern", "Диаграмма направленности", "Polar pattern", "Чувствительность микрофона по углам: кардиоида, суперкардиоида, круговая, восьмёрка.",
             "Mic sensitivity by angle: cardioid, supercardioid, omni, figure-8.", tags: ["cardioid", "кардиоида", "omni"]),
        term("proximity", "Эффект близости", "Proximity effect", "Подъём низа у направленного микрофона при поднесении близко к источнику.",
             "Bass boost of a directional mic close to the source."),
        term("di", "DI-бокс", "DI box", "Преобразует несимметричный высокоомный сигнал в симметричный микрофонный.",
             "Converts unbalanced high-impedance signals to balanced mic level.", practice: LText("См. распайку «DI-бокс».", "See the DI box pinout page.")),
        term("crossover", "Кроссовер (раздел)", "Crossover", "Разделение сигнала по полосам между сабом, НЧ, ВЧ.",
             "Splitting the signal into bands for sub, LF, HF.", tags: ["раздел", "linkwitz", "butterworth"]),
        term("lineArray", "Линейный массив", "Line array", "Вертикальная сборка колонок, работающая как одна; спад около 3 дБ на удвоение расстояния в ближней зоне.",
             "A vertical stack working as one source; about 3 dB per doubling of distance in the near field.", tags: ["line array", "лайн эррей"]),
        term("pointSource", "Точечный источник", "Point source", "Колонка, звук которой спадает на 6 дБ на удвоение расстояния.",
             "A box whose level falls 6 dB per doubling of distance."),
        term("coverage", "Угол покрытия", "Coverage angle", "Углы (гор. × верт.), на краях которых уровень на 6 дБ ниже оси.",
             "Horizontal × vertical angles where the level is 6 dB below on-axis."),
        term("sensitivity", "Чувствительность колонки", "Loudspeaker sensitivity", "SPL на расстоянии 1 м при 1 Вт (или 2,83 В).",
             "SPL at 1 m with 1 W (or 2.83 V) input."),
        term("dampingFactor", "Демпинг-фактор", "Damping factor", "Отношение сопротивления колонки к выходному сопротивлению усилителя с кабелем; влияет на контроль баса.",
             "Load impedance divided by the amp's output impedance plus cable; affects bass control."),
        term("rt60", "Время реверберации RT60", "Reverberation time RT60", "Время спада звука на 60 дБ после остановки источника.",
             "Time for sound to decay by 60 dB after the source stops."),
        term("criticalDistance", "Радиус гулкости", "Critical distance", "Расстояние, на котором прямой и отражённый звук равны по уровню.",
             "Distance where direct and reverberant sound are equal."),
        term("comb", "Гребенчатый фильтр", "Comb filtering", "Провалы АЧХ при сложении одного сигнала с задержанной копией.",
             "Response notches when a signal adds to a delayed copy."),
        term("haas", "Эффект предшествования (Хааса)", "Precedence (Haas) effect", "Ухо локализует звук по первому пришедшему фронту, если задержка второго до ~30 мс.",
             "The ear localises by the first arrival when the second arrives within ~30 ms."),
        term("transferFunction", "Передаточная функция", "Transfer function", "Сравнение выхода системы со входом — АЧХ и фаза; на этом основаны Smaart, SysTune и SSMT.",
             "Comparing a system's output with its input — magnitude and phase; the basis of Smaart, SysTune and SSMT."),
        term("coherence", "Когерентность", "Coherence", "Насколько измерение достоверно на данной частоте (0…1); низкая — шум или отражения.",
             "How trustworthy a measurement is per frequency (0…1); low means noise or reflections."),
        term("pinkNoise", "Розовый шум", "Pink noise", "Шум с равной энергией на октаву — основной тестовый сигнал для настройки систем.",
             "Noise with equal energy per octave — the main test signal for system tuning."),
        term("iem", "In-ear", "In-ear monitors", "Ушные мониторы: радиосистема или провод, личный микс в наушники.",
             "In-ear monitors: wireless or wired, a personal mix in earphones.", tags: ["ушные", "iem"]),
        term("wedge", "Напольный монитор", "Wedge", "Сценический монитор на полу, направленный на артиста.",
             "A floor monitor angled towards the performer.", tags: ["монитор", "клин"]),
        term("sidefill", "Сайдфилл", "Side fill", "Колонки по бокам сцены для общего звука на сцене.", "Speakers at the sides of the stage for overall on-stage sound."),
        term("frontfill", "Фронтфилл", "Front fill", "Колонки на краю сцены для первых рядов.", "Speakers at the stage lip for the front rows."),
        term("riser", "Подиум (райзер)", "Riser", "Возвышение для барабанов или клавиш на сцене.", "A platform for drums or keys on stage."),
        term("rider", "Технический райдер", "Technical rider", "Требования артиста к звуку, свету и сцене: инпут-лист, мониторы, план сцены.",
             "The artist's technical requirements: input list, monitors, stage plot.", tags: ["инпут лист", "input list", "ptch"]),
        term("inputList", "Инпут-лист", "Input list", "Таблица каналов: источник, микрофон, стойка, фантом. В SSMT — функция №2 Ptch.",
             "Channel table: source, mic, stand, phantom. In SSMT — function #2 Ptch.", tags: ["ptch", "патч"]),
        term("patch", "Патч", "Patch", "Соответствие физических входов и выходов каналам пульта.", "Mapping of physical inputs and outputs to console channels.", tags: ["роутинг", "routing"]),
        term("osc", "OSC", "OSC", "Open Sound Control — сетевой протокол управления пультами, светом, медиасерверами.",
             "Open Sound Control — a network protocol for consoles, lighting and media servers."),
        term("msc", "MIDI Show Control", "MIDI Show Control", "Команды запуска кью по MIDI в театральных системах.", "MIDI commands for firing cues in theatre systems."),
        term("ltc", "Таймкод (LTC / MTC)", "Timecode (LTC / MTC)", "Синхронизация шоу по времени: LTC — аудиосигнал, MTC — по MIDI.",
             "Time synchronisation of a show: LTC as audio, MTC over MIDI.", tags: ["timecode", "smpte"]),
        term("ground", "Земляная петля", "Ground loop", "Несколько путей заземления между устройствами — источник фона 50 Гц.",
             "Several ground paths between devices — causing 50 Hz hum.", tags: ["гул", "фон", "hum"]),
    ]
}
