import Foundation

extension HandbookContent {
    static let guides: [HandbookArticle] = [
        HandbookArticle("gainStaging", .guides, title: LText("Гейн-стейджинг", "Gain staging"),
                        subtitle: LText("Правильный уровень на входе и запас", "Right input level and headroom"),
                        tags: ["gain", "гейн", "trim", "уровень", "headroom", "запас", "clip", "перегруз"],
                        blocks: [
                            .steps([LText("Фейдер канала — в 0 дБ (U), EQ и динамика выключены.", "Channel fader at 0 dB (U), EQ and dynamics bypassed."),
                                    LText("Попросите играть так громко, как будет на концерте (не «для проверки»).", "Ask for show-level playing, not soundcheck-quiet."),
                                    LText("Гейном выставьте пики около −18…−12 dBFS (по PFL / метру канала), не выше −6.", "Set gain for peaks around −18…−12 dBFS (PFL / channel meter), never above −6."),
                                    LText("Барабаны и медь — больше запаса: пики до −10 dBFS.", "Drums and brass need more headroom: peaks up to −10 dBFS."),
                                    LText("Громкость в зале регулируйте фейдерами, а не гейном.", "Control the hall level with faders, not gain.")]),
                            .tip(LText("Фейдер у 0 дБ даёт самое точное управление — у краёв шкалы шаг грубее.", "Faders near 0 dB give the finest control — the scale is coarse at the ends.")),
                            .warning(LText("Цифровой клиппинг на входе не исправить ничем после — лучше тише, чем перегруз.", "Digital clipping at the input cannot be undone later — quieter beats clipped.")),
                        ]),
        HandbookArticle("ringOut", .guides, title: LText("Прозвонка мониторов (ring out)", "Ringing out monitors"),
                        subtitle: LText("Убрать заводку до прихода артистов", "Removing feedback before the band arrives"),
                        tags: ["feedback", "заводка", "фидбэк", "ring out", "прозвонка", "мониторы", "wedge", "geq"],
                        blocks: [
                            .steps([LText("Поставьте вокальный микрофон туда, где будет стоять артист, направьте как он будет держать.",
                                          "Place the vocal mic where the artist stands, aimed as it will be held."),
                                    LText("Поднимайте посыл в монитор медленно, до первого «звона».", "Raise the send slowly until the first ring."),
                                    LText("Найдите частоту (RTA пульта или на слух) и вырежьте узкой полосой (Q 6–10) на −3…−6 дБ в графическом / параметрическом EQ монитора.",
                                          "Find the frequency (console RTA or by ear) and cut it narrow (Q 6–10) by −3…−6 dB on the wedge EQ."),
                                    LText("Поднимите уровень ещё на 2–3 дБ и повторите. Обычно хватает 3–6 вырезов.", "Raise 2–3 dB more and repeat. Usually 3–6 cuts are enough."),
                                    LText("Остановитесь на 3–6 дБ ниже точки заводки — это ваш запас.", "Stop 3–6 dB below the feedback point — that is your margin.")]),
                            .bullets([LText("Типичные зоны: 250 Гц (гул), 400–800 Гц (короб), 2–4 кГц (звон), 6–8 кГц (свист).",
                                            "Typical zones: 250 Hz (boom), 400–800 Hz (honk), 2–4 kHz (ring), 6–8 kHz (whistle)."),
                                      LText("Кардиоида: монитор — сзади микрофона (180°). Суперкардиоида: монитор под углом ~120–130°.",
                                            "Cardioid: wedge behind the mic (180°). Supercardioid: wedge at ~120–130°.")]),
                            .warning(LText("Берегите слух и ВЧ-драйверы: поднимайте уровень плавно, держите руку на мьюте.", "Protect ears and HF drivers: raise slowly, keep a hand on mute.")),
                        ]),
        HandbookArticle("lineCheck", .guides, title: LText("Лайн-чек", "Line check"),
                        subtitle: LText("Проверка каждого канала до саундчека", "Checking every channel before soundcheck"),
                        tags: ["line check", "лайнчек", "проверка", "каналы", "патч", "patch", "phantom", "фантом"],
                        blocks: [
                            .steps([LText("Сверьте патч с инпут-листом (Ptch): номер канала, стейджбокс, микрофон.", "Check the patch against the input list (Ptch): channel, stage box, mic."),
                                    LText("Включите фантом +48 В только там, где он нужен (конденсаторы, активные DI).", "Turn on +48 V only where needed (condensers, active DIs)."),
                                    LText("Пройдите по каналам: поскребите / постучите по каждому микрофону, слушайте в PFL.", "Go channel by channel: scratch / tap each mic, listen in PFL."),
                                    LText("Проверьте мониторные посылы: голос в каждый монитор.", "Check the monitor sends: talk into each wedge."),
                                    LText("Проверьте радиосистемы: батареи, частоты, нет ли «дыр» по сцене.", "Check wireless: batteries, frequencies, no drop-outs across the stage.")]),
                            .tip(LText("Помощник на сцене называет номер канала в микрофон — так быстрее и меньше ошибок.", "A stagehand says the channel number into the mic — faster and fewer mistakes.")),
                        ]),
        HandbookArticle("polarity", .guides, title: LText("Полярность и фаза", "Polarity and phase"),
                        subtitle: LText("Почему пропадает низ и как это найти", "Why the low end disappears and how to find it"),
                        tags: ["polarity", "полярность", "phase", "фаза", "invert", "Ø", "snare", "kick"],
                        blocks: [
                            .paragraph(LText("Полярность — это знак сигнала (+/−), фаза — сдвиг во времени, зависящий от частоты. Кнопка Ø на пульте переворачивает полярность.",
                                             "Polarity is the sign of the signal (+/−); phase is a frequency-dependent time shift. The Ø button flips polarity.")),
                            .bullets([LText("Малый барабан сверху и снизу — нижний микрофон почти всегда переворачивают.", "Snare top and bottom — the bottom mic is almost always flipped."),
                                      LText("Бочка внутри и снаружи — сравните оба положения Ø: оставьте то, где больше низа.", "Kick in and out — try both Ø positions, keep the one with more low end."),
                                      LText("DI и микрофон на одном инструменте — выровняйте задержкой (1–3 мс) и проверьте полярность.", "DI plus mic on one instrument — align with delay (1–3 ms) and check polarity."),
                                      LText("Саб и топ — проверка по SSMT (функция №1) или по спаду на частоте раздела.", "Sub and top — check with SSMT (function #1) or by the dip at the crossover.")]),
                            .tip(LText("Правило: включите оба микрофона, нажмите Ø на одном — выберите положение, где звук плотнее и громче.",
                                       "Rule: open both mics, flip one — keep whichever is fuller and louder.")),
                        ]),
        HandbookArticle("subAlign", .guides, title: LText("Выравнивание саба и топа", "Aligning sub and top"),
                        subtitle: LText("Задержка и полярность на разделе", "Delay and polarity at the crossover"),
                        tags: ["sub", "саб", "alignment", "выравнивание", "crossover", "кроссовер", "delay"],
                        blocks: [
                            .steps([LText("Выберите точку измерения — обычно 2/3 глубины зала по оси системы.", "Pick the measurement spot — usually 2/3 of the room depth on the system axis."),
                                    LText("Измерьте отдельно топ и саб (фаза и АЧХ).", "Measure the top and the sub on their own (phase and magnitude)."),
                                    LText("Задержите того, кто «раньше», чтобы фазы совпадали в районе раздела (обычно 80–120 Гц).",
                                          "Delay whichever is early so the phases match around the crossover (usually 80–120 Hz)."),
                                    LText("Включите оба: сумма на разделе должна быть +5…+6 дБ к каждому по отдельности.", "Play both: the sum at crossover should be +5…+6 dB over each one alone.")]),
                            .tip(LText("Функция №1 SSMT делает это автоматически по шагам.", "SSMT function #1 does this step by step automatically.")),
                        ]),
        HandbookArticle("delayTowers", .guides, title: LText("Дилей-линии", "Delay towers"),
                        subtitle: LText("Задержка и уровень дополнительных колонок", "Delay and level of fill speakers"),
                        tags: ["delay tower", "дилей", "fill", "front fill", "outfill", "задержка", "haas", "хаас"],
                        blocks: [
                            .steps([LText("Измерьте расстояние от основного портала до дилей-колонки (или до зрителя, если считать для точки).",
                                          "Measure the distance from the main PA to the delay speaker (or to the listener for a point)."),
                                    LText("Задержка = расстояние / скорость звука (калькулятор «Задержка по расстоянию»).", "Delay = distance / speed of sound (\"Delay from distance\" calculator)."),
                                    LText("Добавьте 5–15 мс, чтобы звук локализовался на сцене (эффект предшествования).", "Add 5–15 ms so the sound localises on stage (precedence effect)."),
                                    LText("Уровень дилея — так, чтобы в его зоне он был равен или чуть тише портала (не громче на 6+ дБ).",
                                          "Delay level — equal to or slightly below the main PA in its zone (never 6+ dB louder).")]),
                            .warning(LText("Учитывайте температуру: от утра к вечеру скорость звука меняется, проверяйте перед шоу.", "Temperature matters: the speed of sound changes from morning to evening — check before the show.")),
                        ]),
        HandbookArticle("eqBasics", .guides, title: LText("Эквализация: где что живёт", "EQ: where things live"),
                        subtitle: LText("Частоты инструментов и голоса", "Frequencies of instruments and voice"),
                        tags: ["eq", "эквалайзер", "частоты", "frequency", "эквализация", "vocal", "kick", "snare"],
                        blocks: [
                            .table(header: [LText("Источник", "Source"), LText("Что резать", "Cut"), LText("Что поднимать", "Boost")],
                                   rows: [[LText("Вокал", "Vocal"), LText("HPF 80–120 Гц; 200–400 Гц «бубнение»", "HPF 80–120 Hz; 200–400 Hz mud"), LText("2–5 кГц разборчивость, 8–12 кГц воздух", "2–5 kHz intelligibility, 8–12 kHz air")],
                                          [LText("Бочка", "Kick"), LText("300–500 Гц «картон»", "300–500 Hz cardboard"), LText("50–80 Гц тело, 2–4 кГц щелчок", "50–80 Hz body, 2–4 kHz click")],
                                          [LText("Малый", "Snare"), LText("400–800 Гц «коробка»", "400–800 Hz box"), LText("150–250 Гц тело, 5 кГц щелчок", "150–250 Hz body, 5 kHz crack")],
                                          [LText("Томы", "Toms"), LText("300–600 Гц", "300–600 Hz"), LText("80–150 Гц тело, 3–5 кГц атака", "80–150 Hz body, 3–5 kHz attack")],
                                          [LText("Оверхеды", "Overheads"), LText("HPF 150–300 Гц", "HPF 150–300 Hz"), LText("8–12 кГц тарелки", "8–12 kHz cymbals")],
                                          [LText("Бас", "Bass"), LText("200–300 Гц гул", "200–300 Hz boom"), LText("60–100 Гц, 700 Гц–1 кГц читаемость", "60–100 Hz, 700 Hz–1 kHz definition")],
                                          [LText("Гитара (комбик)", "Guitar (amp)"), LText("HPF 80–100 Гц; 2–3 кГц резкость", "HPF 80–100 Hz; 2–3 kHz harshness"), LText("1–2 кГц середина", "1–2 kHz presence")],
                                          [LText("Акустическая гитара", "Acoustic guitar"), LText("HPF 100 Гц; 200 Гц бубнение", "HPF 100 Hz; 200 Hz boom"), LText("5–8 кГц струны", "5–8 kHz strings")]]),
                            .tip(LText("Сначала режьте лишнее, потом поднимайте. Узкие подъёмы — источник заводки.", "Cut first, boost later. Narrow boosts invite feedback.")),
                        ]),
        HandbookArticle("compressor", .guides, title: LText("Компрессор: стартовые настройки", "Compressor: starting points"),
                        subtitle: LText("Порог, ratio, атака, восстановление", "Threshold, ratio, attack, release"),
                        tags: ["compressor", "компрессор", "ratio", "attack", "release", "threshold", "порог", "динамика"],
                        blocks: [
                            .table(header: [LText("Источник", "Source"), LText("Ratio"), LText("Атака", "Attack"), LText("Восстановление", "Release"), LText("Подавление", "Gain reduction")],
                                   rows: [[LText("Вокал", "Vocal"), LText("3:1"), LText("5–10 мс", "5–10 ms"), LText("80–150 мс", "80–150 ms"), LText("3–6 дБ", "3–6 dB")],
                                          [LText("Бас", "Bass"), LText("4:1"), LText("10–30 мс", "10–30 ms"), LText("100–200 мс", "100–200 ms"), LText("3–6 дБ", "3–6 dB")],
                                          [LText("Бочка", "Kick"), LText("4:1"), LText("10–30 мс", "10–30 ms"), LText("50–100 мс", "50–100 ms"), LText("3–6 дБ", "3–6 dB")],
                                          [LText("Малый", "Snare"), LText("3:1"), LText("5–20 мс", "5–20 ms"), LText("80–120 мс", "80–120 ms"), LText("2–5 дБ", "2–5 dB")],
                                          [LText("Акустика", "Acoustic"), LText("2:1"), LText("10–20 мс", "10–20 ms"), LText("100–200 мс", "100–200 ms"), LText("2–4 дБ", "2–4 dB")],
                                          [LText("Мастер-шина", "Master bus"), LText("2:1"), LText("30 мс", "30 ms"), LText("Авто", "Auto"), LText("1–3 дБ", "1–3 dB")]]),
                            .tip(LText("Длинная атака оставляет щелчок (барабаны), короткая — сглаживает. Восстановление — чтобы стрелка успевала вернуться к следующей ноте.",
                                       "A slow attack keeps the click (drums), a fast one smooths. Set release so the meter returns before the next note.")),
                        ]),
        HandbookArticle("iem", .guides, title: LText("Ушные мониторы (in-ear)", "In-ear monitors"),
                        subtitle: LText("Как собрать удобный микс", "Building a comfortable mix"),
                        tags: ["iem", "in-ear", "ушные", "мониторы", "радио", "ambience", "амбиенс"],
                        blocks: [
                            .bullets([LText("Начинайте с собственного голоса/инструмента артиста, затем ритм-секция, потом остальное.", "Start with the artist's own voice/instrument, then the rhythm section, then the rest."),
                                      LText("Ambience (микрофоны на зал) возвращает ощущение сцены — 1–2 микрофона, ВЧ-фильтр.", "Ambience mics (towards the audience) restore the room — 1–2 mics, high-pass filtered."),
                                      LText("Стерео-микс с панорамой удобнее и тише, чем моно.", "A panned stereo mix is clearer and allows lower levels than mono."),
                                      LText("Лимитер на шине ушного монитора защищает слух от резких хлопков.", "A limiter on the IEM bus protects hearing from sudden bangs.")]),
                            .warning(LText("Перед вставкой наушников — минимальная громкость на бельтпаке. Резкие сигналы в ушах опаснее, чем от колонок.",
                                           "Turn the beltpack down before putting the earpieces in. Sudden peaks in the ears are more dangerous than from speakers.")),
                        ]),
        HandbookArticle("wireless", .guides, title: LText("Радиосистемы: частоты и батареи", "Wireless: frequencies and batteries"),
                        subtitle: LText("Как избежать пропаданий", "How to avoid drop-outs"),
                        tags: ["wireless", "радио", "радиосистема", "частоты", "frequency", "scan", "скан", "батареи", "антенны"],
                        blocks: [
                            .steps([LText("Сканируйте эфир на площадке (функция scan приёмника или программа производителя).", "Scan the RF on site (receiver scan or the maker's software)."),
                                    LText("Раздайте частоты из совместимой группы — не выбирайте вручную «на глаз».", "Assign frequencies from one compatible group — never pick by eye."),
                                    LText("Антенны — в прямой видимости сцены, не за металлом, на расстоянии от цифровой техники и LED-экранов.",
                                          "Antennas in line of sight to the stage, not behind metal, away from digital gear and LED walls."),
                                    LText("Новые батареи на каждое шоу (или аккумуляторы, заряженные полностью).", "Fresh batteries each show (or fully charged packs).")]),
                            .tip(LText("Проверьте покрытие: пройдите с передатчиком по всей сцене, глядя на индикатор RF.", "Walk the whole stage with the transmitter watching RF level.")),
                        ]),
        HandbookArticle("groundHum", .guides, title: LText("Фон и гул: как найти и убрать", "Hum and buzz: finding the cause"),
                        subtitle: LText("Земляные петли, наводки, питание", "Ground loops, interference, power"),
                        tags: ["hum", "гул", "фон", "buzz", "ground loop", "земляная петля", "наводка", "50 hz"],
                        blocks: [
                            .steps([LText("Отключайте источники по одному, пока фон не пропадёт.", "Disconnect sources one by one until the hum stops."),
                                    LText("Для несимметричных источников — DI с ground lift.", "For unbalanced sources — a DI with ground lift."),
                                    LText("Звук и свет — с разных линий питания, но общий контур заземления.", "Power sound and lighting from separate circuits but one earthing system."),
                                    LText("Сигнальные кабели не тяните параллельно силовым; пересекайте под прямым углом.", "Do not run signal next to power; cross at right angles.")]),
                            .warning(LText("Никогда не отключайте защитную землю в сетевой вилке, чтобы убрать фон — это опасно для жизни.",
                                           "Never lift the safety earth on a mains plug to cure hum — it can be lethal.")),
                        ]),
        HandbookArticle("micChoice", .guides, title: LText("Микрофоны для барабанов и бэнда", "Mics for drums and band"),
                        subtitle: LText("Типовая расстановка", "Typical choices"),
                        tags: ["microphone", "микрофон", "drums", "барабаны", "sm57", "sm58", "beta 52", "e604", "расстановка"],
                        blocks: [
                            .table(header: [LText("Источник", "Source"), LText("Типично", "Typical"), LText("Положение", "Placement")],
                                   rows: [[LText("Бочка", "Kick"), LText("Beta 91A внутри, Beta 52A / D6 снаружи", "Beta 91A inside, Beta 52A / D6 outside"), LText("В отверстии, 5–10 см от пластика", "In the port, 5–10 cm from the head")],
                                          [LText("Малый", "Snare"), LText("SM57, e904", "SM57, e904"), LText("2–4 см над ободом, на центр", "2–4 cm above the rim, aimed at centre")],
                                          [LText("Томы", "Toms"), LText("e604, Beta 98", "e604, Beta 98"), LText("На обод, 3–5 см", "Clipped on the rim, 3–5 cm")],
                                          [LText("Хай-хэт", "Hi-hat"), LText("Конденсатор (KM184, C451)", "Condenser (KM184, C451)"), LText("Сверху, от малого", "From above, away from the snare")],
                                          [LText("Оверхеды", "Overheads"), LText("Пара конденсаторов", "Condenser pair"), LText("Равное расстояние до малого", "Equal distance to the snare")],
                                          [LText("Гитарный комбик", "Guitar amp"), LText("SM57, e906", "SM57, e906"), LText("Край диффузора, вплотную", "Cone edge, close")],
                                          [LText("Вокал", "Vocal"), LText("SM58, Beta 58A, e935", "SM58, Beta 58A, e935"), LText("Губы у сетки", "Lips at the grille")]]),
                        ]),
    ]
}
