import Foundation

extension HandbookContent {
    private static func manual(_ maker: String, _ url: String) -> HandbookBlock {
        .link(title: LText("Официальные руководства и прошивки — сайт \(maker)", "Official manuals and firmware — \(maker) website"), url: url)
    }

    private static let onlineNote = HandbookBlock.tip(LText(
        "Это краткая шпаргалка SSMT. Точные названия меню зависят от версии прошивки — сверяйтесь с руководством вашей версии.",
        "This is an SSMT cheat sheet. Menu names depend on the firmware — check the manual for your version."))

    static let consoles: [HandbookArticle] = [
        HandbookArticle("x32", .consoles, title: LText("Behringer X32 / Midas M32", "Behringer X32 / Midas M32"),
                        subtitle: LText("32 входных канала, 16 шин, 2 × AES50", "32 input channels, 16 buses, 2 × AES50"),
                        tags: ["x32", "m32", "behringer", "midas", "бэрингер", "мидас", "aes50", "s16", "dl16", "x32 edit", "mixing station"],
                        blocks: [
                            .heading(LText("Главное", "Basics")),
                            .bullets([LText("32 моно-канала, 8 aux-входов, 16 мик/шин, 6 матриц, главный стерео и моно/центр, 8 DCA, 6 мьют-групп.",
                                            "32 mono channels, 8 aux inputs, 16 mix buses, 6 matrices, main stereo and mono/centre, 8 DCAs, 6 mute groups."),
                                      LText("Стейджбоксы по AES50 (порт A / B): S16, S32, DL16, DL32.", "Stage boxes over AES50 (port A / B): S16, S32, DL16, DL32."),
                                      LText("Удалённо: X32-Edit (компьютер), X32-Mix / M32-Mix (iPad), Mixing Station. Протокол OSC, порт 10023.",
                                            "Remote: X32-Edit (computer), X32-Mix / M32-Mix (iPad), Mixing Station. OSC protocol, port 10023.")]),
                            .heading(LText("Как сделать", "How to")),
                            .bullets([LText("Входы на каналы: ROUTING → Home → блоки входов по 8 (Local, AES50 A/B, Card).", "Inputs to channels: ROUTING → Home → input blocks of 8 (Local, AES50 A/B, Card)."),
                                      LText("Гейн стейджбокса — в канале (Preamp), если блок назначен на AES50.", "Stage box gain is in the channel (Preamp) when the block is on AES50."),
                                      LText("Сцены: VIEW в секции Scenes; Safes защищают параметры от загрузки сцены.", "Scenes: VIEW in the Scenes section; Safes protect parameters from recall."),
                                      LText("Копировать настройки канала: Utility → Copy в экране канала.", "Copy a channel: Utility → Copy on the channel screen."),
                                      LText("Мониторы: «Sends on Fader» — фейдеры показывают посылы в выбранную шину.", "Monitors: Sends on Fader — faders show the sends to the selected bus.")]),
                            .tip(LText("SSMT FOH Assist работает с этим пультом по сети (функция №4).", "SSMT FOH Assist works with this console over the network (function #4).")),
                            onlineNote,
                            manual("Behringer", "https://www.behringer.com"),
                            manual("Midas", "https://www.midasconsoles.com"),
                        ]),
        HandbookArticle("xair", .consoles, title: LText("Behringer X Air / Midas MR", "Behringer X Air / Midas MR"),
                        subtitle: LText("XR12, XR16, XR18, MR18 — пульт без поверхности", "XR12, XR16, XR18, MR18 — surface-less mixer"),
                        tags: ["x air", "xr18", "xr16", "xr12", "mr18", "mr12", "behringer", "midas", "wifi", "планшет"],
                        blocks: [
                            .bullets([LText("Управление только с планшета / компьютера: X Air Edit, X Air (iPad/Android), Mixing Station.",
                                            "Controlled only from a tablet / computer: X Air Edit, X Air app, Mixing Station."),
                                      LText("Встроенная точка доступа Wi-Fi — для серьёзной работы подключайте внешний роутер по кабелю.",
                                            "Built-in Wi-Fi access point — for real shows connect an external router by cable."),
                                      LText("OSC, порт 10024. Сцены и снапшоты — в приложении.", "OSC, port 10024. Scenes and snapshots in the app.")]),
                            .warning(LText("Без поверхности главный риск — потеря связи. Держите резервный планшет и кабельное подключение.",
                                           "With no surface the main risk is losing the link. Keep a spare tablet and a wired connection.")),
                            onlineNote,
                            manual("Behringer", "https://www.behringer.com"),
                        ]),
        HandbookArticle("wing", .consoles, title: LText("Behringer WING", "Behringer WING"),
                        subtitle: LText("Флагман Behringer с сенсорным экраном", "Behringer flagship with a touch screen"),
                        tags: ["wing", "behringer", "вин", "aes50", "stagecon", "wing edit"],
                        blocks: [
                            .bullets([LText("Стерео-каналы и шины, гибкий роутинг источников, AES50 и StageConnect для стейджбоксов.",
                                            "Stereo channels and buses, flexible source routing, AES50 and StageConnect for stage boxes."),
                                      LText("Удалённо: WING Edit, WING Co-Pilot, Mixing Station.", "Remote: WING Edit, WING Co-Pilot, Mixing Station."),
                                      LText("Пользовательские слои и кнопки — настройте под свой воркфлоу заранее.", "Custom layers and buttons — set them up for your workflow beforehand.")]),
                            .tip(LText("Протокол отличается от X32 — FOH Assist SSMT пока поддерживает X32/M32 и X Air.", "The protocol differs from X32 — SSMT FOH Assist currently supports X32/M32 and X Air.")),
                            onlineNote,
                            manual("Behringer", "https://www.behringer.com"),
                        ]),
        HandbookArticle("yamahaCLQL", .consoles, title: LText("Yamaha CL / QL", "Yamaha CL / QL"),
                        subtitle: LText("Dante, Centralogic, Rio", "Dante, Centralogic, Rio"),
                        tags: ["yamaha", "ямаха", "cl5", "cl3", "cl1", "ql5", "ql1", "dante", "rio", "centralogic", "stagemix"],
                        blocks: [
                            .bullets([LText("Dante встроен; стейджбоксы Rio / Tio. Патч — через Dante Controller и экран Dante Setup пульта.",
                                            "Dante built in; Rio / Tio stage boxes. Patch via Dante Controller and the console's Dante Setup screen."),
                                      LText("Selected Channel — все параметры канала ручками справа; Centralogic — 8 каналов на экране.",
                                            "Selected Channel — every channel parameter on the knobs; Centralogic — 8 channels on screen."),
                                      LText("Сцены: Scene Memory, Recall Safe (защита) и Focus (что загружать).", "Scenes: Scene Memory, Recall Safe (protect) and Focus (what to recall)."),
                                      LText("Удалённо: CL/QL Editor (компьютер), CL/QL StageMix (iPad).", "Remote: CL/QL Editor (computer), CL/QL StageMix (iPad).")]),
                            .tip(LText("Gain Compensation на стороне Rio позволяет FOH и мониторам делить стейджбокс без влияния друг на друга.",
                                       "Gain Compensation on the Rio lets FOH and monitors share a stage box without affecting each other.")),
                            onlineNote,
                            manual("Yamaha", "https://www.yamaha.com"),
                        ]),
        HandbookArticle("yamahaTF", .consoles, title: LText("Yamaha TF / DM3", "Yamaha TF / DM3"),
                        subtitle: LText("Компактные цифровые пульты Yamaha", "Yamaha compact digital consoles"),
                        tags: ["yamaha", "tf1", "tf3", "tf5", "dm3", "touchflow", "tf editor"],
                        blocks: [
                            .bullets([LText("TouchFlow: сенсорный экран, QuickPro-пресеты для типовых источников.", "TouchFlow: touch screen, QuickPro presets for common sources."),
                                      LText("Удалённо: TF Editor, TF StageMix; DM3 — DM3 Editor, StageMix.", "Remote: TF Editor, TF StageMix; DM3 — DM3 Editor, StageMix."),
                                      LText("Стейджбоксы Tio по Dante (через карту / встроенный Dante на моделях с ним).", "Tio stage boxes over Dante (card or built-in Dante where available).")]),
                            onlineNote,
                            manual("Yamaha", "https://www.yamaha.com"),
                        ]),
        HandbookArticle("ahSQ", .consoles, title: LText("Allen & Heath SQ", "Allen & Heath SQ"),
                        subtitle: LText("SQ-5, SQ-6, SQ-7 — 48 каналов, 96 кГц", "SQ-5, SQ-6, SQ-7 — 48 channels, 96 kHz"),
                        tags: ["allen heath", "аллен хит", "sq5", "sq6", "sq7", "slink", "dx168", "ar2412", "sq mixpad", "sq4you"],
                        blocks: [
                            .bullets([LText("SLink — стейджбоксы dSnake/DX (AR2412, AB168, DX168, DX32).", "SLink — dSnake/DX stage boxes (AR2412, AB168, DX168, DX32)."),
                                      LText("Удалённо: SQ MixPad (iPad), SQ4You (личные мониторы), MixPad (Windows/macOS).", "Remote: SQ MixPad (iPad), SQ4You (personal monitors), MixPad (Windows/macOS)."),
                                      LText("Сцены + Scene Safes и фильтры для отдельных сцен.", "Scenes with Scene Safes and per-scene filters."),
                                      LText("Пользователи с правами (Admin / User) — блокировка функций для приглашённых звукорежиссёров.",
                                            "User profiles (Admin / User) lock functions for guest engineers.")]),
                            onlineNote,
                            manual("Allen & Heath", "https://www.allen-heath.com"),
                        ]),
        HandbookArticle("ahDlive", .consoles, title: LText("Allen & Heath dLive / Avantis", "Allen & Heath dLive / Avantis"),
                        subtitle: LText("MixRack + поверхность / 64 канала Avantis", "MixRack + surface / 64-channel Avantis"),
                        tags: ["dlive", "avantis", "allen heath", "mixrack", "director", "gigaace", "dx32", "dm64"],
                        blocks: [
                            .bullets([LText("dLive: обработка в MixRack, поверхность — управление; до 128 входов.", "dLive: processing in the MixRack, the surface controls; up to 128 inputs."),
                                      LText("Avantis: 64 канала, два сенсорных экрана, Continuity UI.", "Avantis: 64 channels, two touch screens, Continuity UI."),
                                      LText("dLive Director / Avantis Director — офлайн-подготовка и удалённое управление.", "dLive Director / Avantis Director — offline prep and remote control."),
                                      LText("gigaACE — связь поверхность–рэк и FOH–мониторы.", "gigaACE links surface to rack and FOH to monitors.")]),
                            onlineNote,
                            manual("Allen & Heath", "https://www.allen-heath.com"),
                        ]),
        HandbookArticle("digico", .consoles, title: LText("DiGiCo SD / Quantum", "DiGiCo SD / Quantum"),
                        subtitle: LText("Снапшоты, макросы, Optocore", "Snapshots, macros, Optocore"),
                        tags: ["digico", "диджико", "sd5", "sd7", "sd9", "sd10", "sd12", "quantum", "optocore", "sd-rack", "snapshot", "снапшот"],
                        blocks: [
                            .bullets([LText("Снапшоты с глобальным и локальным Scope — что именно загружает каждый снапшот.",
                                            "Snapshots with global and per-snapshot Scope — what each snapshot recalls."),
                                      LText("Macro — кнопки на любую последовательность действий.", "Macros — buttons for any sequence of actions."),
                                      LText("Стейджбоксы SD-Rack / SD-MiNi Rack по MADI или Optocore.", "SD-Rack / SD-MiNi Rack stage boxes over MADI or Optocore."),
                                      LText("Офлайн-редактор DiGiCo Offline Software для подготовки шоу.", "DiGiCo Offline Software for show prep.")]),
                            .warning(LText("Перед загрузкой чужой сессии сохраните свою и проверьте, что I/O на другом пульте совпадает.",
                                           "Before loading someone else's session, save yours and check that the I/O matches.")),
                            onlineNote,
                            manual("DiGiCo", "https://www.digico.biz"),
                        ]),
        HandbookArticle("midasPro", .consoles, title: LText("Midas PRO / HD96", "Midas PRO / HD96"),
                        subtitle: LText("Большие пульты Midas", "Midas large-format consoles"),
                        tags: ["midas", "pro2", "pro6", "pro9", "hd96", "dl231", "dl251", "neutron"],
                        blocks: [
                            .bullets([LText("Стейджбоксы DL-серии по AES50, мониторный сплит — через второй порт AES50.", "DL-series stage boxes over AES50, monitor split via the second AES50 port."),
                                      LText("POP-группы и VCA — быстрые слои для управления группами каналов.", "POP groups and VCAs — quick layers for groups of channels."),
                                      LText("Офлайн-редакторы есть для обеих линеек.", "Offline editors exist for both ranges.")]),
                            onlineNote,
                            manual("Midas", "https://www.midasconsoles.com"),
                        ]),
        HandbookArticle("soundcraft", .consoles, title: LText("Soundcraft Si / Vi / Ui", "Soundcraft Si / Vi / Ui"),
                        subtitle: LText("От планшетных Ui до турового Vi", "From tablet Ui to touring Vi"),
                        tags: ["soundcraft", "саундкрафт", "si expression", "vi1000", "vi3000", "ui24r", "ui16", "ui12"],
                        blocks: [
                            .bullets([LText("Ui12/16/24R — управление из браузера по Wi-Fi, без приложения.", "Ui12/16/24R — controlled from a web browser over Wi-Fi, no app."),
                                      LText("Si Expression — фейдеры с FaderGlow; стейджбоксы Mini Stagebox по MADI-карте.", "Si Expression — FaderGlow faders; Mini Stagebox over a MADI card."),
                                      LText("Vi — Vistonics: ручки прямо на сенсорном экране.", "Vi — Vistonics: knobs right on the touch screen.")]),
                            onlineNote,
                            manual("Soundcraft", "https://www.soundcraft.com"),
                        ]),
        HandbookArticle("yamahaDM7", .consoles, title: LText("Yamaha DM7", "Yamaha DM7"),
                        subtitle: LText("DM7 и DM7 Compact — современная серия Yamaha", "DM7 and DM7 Compact — Yamaha's current series"),
                        tags: ["yamaha", "ямаха", "dm7", "dm7 compact", "dante", "theatre package", "broadcast package"],
                        blocks: [
                            .bullets([LText("Dante встроен; стейджбоксы Rio / Tio, патч — в Dante Controller и экране Dante пульта.",
                                            "Dante built in; Rio / Tio stage boxes, patched in Dante Controller and the console's Dante screen."),
                                      LText("Сенсорные экраны с привычной для Yamaha логикой Selected Channel.", "Touch screens with the familiar Yamaha Selected Channel logic."),
                                      LText("Дополнительные пакеты функций для театра и вещания (Theatre / Broadcast Package).", "Optional feature packages for theatre and broadcast (Theatre / Broadcast Package)."),
                                      LText("Удалённо: DM7 Editor (компьютер), DM7 StageMix (iPad).", "Remote: DM7 Editor (computer), DM7 StageMix (iPad).")]),
                            onlineNote,
                            manual("Yamaha", "https://www.yamaha.com"),
                        ]),
        HandbookArticle("yamahaRivage", .consoles, title: LText("Yamaha RIVAGE PM", "Yamaha RIVAGE PM"),
                        subtitle: LText("PM3, PM5, PM7, PM10 — туровый флагман", "PM3, PM5, PM7, PM10 — touring flagship"),
                        tags: ["yamaha", "rivage", "pm10", "pm7", "pm5", "pm3", "twinlane", "rpio", "silk", "dsp-rx"],
                        blocks: [
                            .bullets([LText("Поверхность + DSP-движок (DSP-RX / DSP-RX-EX); стейджбоксы RPio и Rio по TWINLANe или Dante.",
                                            "Surface + DSP engine (DSP-RX / DSP-RX-EX); RPio and Rio stage boxes over TWINLANe or Dante."),
                                      LText("Предусилители с обработкой Rupert Neve Designs SILK, встроенные плагины.", "Preamps with Rupert Neve Designs SILK processing, built-in plug-ins."),
                                      LText("RIVAGE PM Editor — подготовка шоу офлайн и удалённое управление; StageMix — с iPad.",
                                            "RIVAGE PM Editor — offline prep and remote control; StageMix on iPad."),
                                      LText("Сцены с Recall Safe и Focus, как на CL/QL — привычно для пользователей Yamaha.", "Scenes with Recall Safe and Focus, as on CL/QL.")]),
                            onlineNote,
                            manual("Yamaha", "https://www.yamaha.com"),
                        ]),
        HandbookArticle("ahQu", .consoles, title: LText("Allen & Heath Qu", "Allen & Heath Qu"),
                        subtitle: LText("Qu-16/24/32 и новое поколение Qu-5/6/7", "Qu-16/24/32 and the new Qu-5/6/7"),
                        tags: ["allen heath", "аллен хит", "qu16", "qu24", "qu32", "qu-5", "qu-6", "qu-7", "qu-pad", "qu-you", "dsnake", "ar2412"],
                        blocks: [
                            .bullets([LText("Стейджбоксы dSnake (AR2412, AR84, AB168) по Cat5.", "dSnake stage boxes (AR2412, AR84, AB168) over Cat5."),
                                      LText("Многоканальная запись на USB-накопитель и по USB в компьютер.", "Multitrack recording to a USB drive and over USB to a computer."),
                                      LText("Удалённо: Qu-Pad (iPad), Qu-You (личные мониторы музыкантов).", "Remote: Qu-Pad (iPad), Qu-You (musicians' personal monitors)."),
                                      LText("Сцены с фильтрами Recall и Safes.", "Scenes with recall filters and safes.")]),
                            .tip(LText("У нового поколения Qu-5/6/7 другие приложения и возможности — проверьте руководство именно вашей модели.",
                                       "The new Qu-5/6/7 have different apps and features — check the manual for your exact model.")),
                            onlineNote,
                            manual("Allen & Heath", "https://www.allen-heath.com"),
                        ]),
        HandbookArticle("ahCQ", .consoles, title: LText("Allen & Heath CQ", "Allen & Heath CQ"),
                        subtitle: LText("CQ-12T, CQ-18T, CQ-20B — компактные с сенсорным экраном", "CQ-12T, CQ-18T, CQ-20B — compact, touch screen"),
                        tags: ["allen heath", "cq", "cq-12t", "cq-18t", "cq-20b", "cq mixpad", "cq4you", "bluetooth"],
                        blocks: [
                            .bullets([LText("Мастера настройки (Quick Mode) для быстрого старта, полный режим для тонкой работы.", "Setup wizards (Quick mode) for a fast start, full mode for detail."),
                                      LText("CQ-20B — без экрана, только управление с планшета/компьютера.", "CQ-20B has no screen — tablet/computer control only."),
                                      LText("Удалённо: CQ MixPad, CQ4You (личные мониторы).", "Remote: CQ MixPad, CQ4You (personal monitors)."),
                                      LText("Bluetooth-вход для фоновой музыки.", "Bluetooth input for background music.")]),
                            onlineNote,
                            manual("Allen & Heath", "https://www.allen-heath.com"),
                        ]),
        HandbookArticle("avidS6L", .consoles, title: LText("Avid VENUE S6L", "Avid VENUE S6L"),
                        subtitle: LText("Туровый пульт с плагинами AAX и Pro Tools", "Touring console with AAX plug-ins and Pro Tools"),
                        tags: ["avid", "venue", "s6l", "e6l", "stage 64", "stage 16", "aax", "pro tools", "virtual soundcheck"],
                        blocks: [
                            .bullets([LText("Поверхность S6L + движок E6L; стейджбоксы Stage 64 / Stage 16 по AVB.", "S6L surface + E6L engine; Stage 64 / Stage 16 stage boxes over AVB."),
                                      LText("Плагины AAX DSP прямо в пульте.", "AAX DSP plug-ins inside the console."),
                                      LText("Запись в Pro Tools и виртуальный саундчек (воспроизведение записи на входы каналов).",
                                            "Recording to Pro Tools and virtual soundcheck (playing a recording back into the channels)."),
                                      LText("VENUE Software — офлайн-подготовка шоу на компьютере.", "VENUE Software — offline show prep on a computer.")]),
                            onlineNote,
                            manual("Avid", "https://www.avid.com"),
                        ]),
        HandbookArticle("sslLive", .consoles, title: LText("SSL Live", "SSL Live"),
                        subtitle: LText("L100, L200, L350, L550, L650", "L100, L200, L350, L550, L650"),
                        tags: ["ssl", "solid state logic", "ssl live", "l100", "l200", "l350", "l550", "l650", "solsa", "taco", "blacklight", "stageblox"],
                        blocks: [
                            .bullets([LText("Входы-выходы по Dante, MADI и Blacklight; стейджбоксы SSL (линейка Stageblox и Dante-боксы).",
                                            "I/O over Dante, MADI and Blacklight; SSL stage boxes (Stageblox and Dante boxes)."),
                                      LText("Стэмы (Stems) и запросы (Queries) — гибкая организация шин и быстрый доступ к каналам.",
                                            "Stems and Queries — flexible bus organisation and quick channel access."),
                                      LText("SOLSA — офлайн-редактор и удалённое управление с компьютера; TaCo — с планшета.",
                                            "SOLSA — offline editor and remote control from a computer; TaCo — from a tablet.")]),
                            onlineNote,
                            manual("Solid State Logic", "https://www.solidstatelogic.com"),
                        ]),
        HandbookArticle("presonusSL3", .consoles, title: LText("PreSonus StudioLive Series III", "PreSonus StudioLive Series III"),
                        subtitle: LText("16, 24, 32, 32S/SC/SX, 64S", "16, 24, 32, 32S/SC/SX, 64S"),
                        tags: ["presonus", "пресонус", "studiolive", "series iii", "32s", "64s", "uc surface", "capture", "avb", "nsb"],
                        blocks: [
                            .bullets([LText("Многоканальная запись: Capture (компьютер) и на SD-карту в пульте.", "Multitrack recording: Capture (computer) and to the SD card in the console."),
                                      LText("Стейджбоксы NSB по AVB.", "NSB stage boxes over AVB."),
                                      LText("Удалённо: UniversalControl / UC Surface (компьютер, планшет), QMix-UC (личные мониторы, телефон).",
                                            "Remote: UniversalControl / UC Surface (computer, tablet), QMix-UC (personal monitors, phone)."),
                                      LText("Fat Channel — обработка канала с моделями классических приборов.", "Fat Channel — channel processing with models of classic units.")]),
                            onlineNote,
                            manual("PreSonus", "https://www.presonus.com"),
                        ]),
        HandbookArticle("mackieDL", .consoles, title: LText("Mackie DL32S / DL16S / DL32R", "Mackie DL32S / DL16S / DL32R"),
                        subtitle: LText("Пульт-рэк с управлением с iPad", "Rack mixer controlled from an iPad"),
                        tags: ["mackie", "маки", "dl32s", "dl16s", "dl32r", "master fader", "ipad", "wifi"],
                        blocks: [
                            .bullets([LText("Поверхности нет — управление из приложения Master Fader (iPad, компьютер).", "No surface — controlled from the Master Fader app (iPad, computer)."),
                                      LText("Многоканальная запись на USB-диск и по USB в компьютер.", "Multitrack recording to a USB drive and over USB to a computer."),
                                      LText("Встроенный Wi-Fi; для шоу надёжнее внешний роутер по кабелю.", "Built-in Wi-Fi; an external wired router is more reliable for shows.")]),
                            .warning(LText("Как у любого пульта без поверхности: держите запасной планшет и кабельное подключение.",
                                           "As with any surface-less mixer: keep a spare tablet and a wired link.")),
                            onlineNote,
                            manual("Mackie", "https://mackie.com"),
                        ]),
        HandbookArticle("digicoS", .consoles, title: LText("DiGiCo S21 / S31", "DiGiCo S21 / S31"),
                        subtitle: LText("Младшая линейка DiGiCo", "DiGiCo's entry range"),
                        tags: ["digico", "диджико", "s21", "s31", "dmi", "snapshot"],
                        blocks: [
                            .bullets([LText("Два сенсорных экрана, работа со снапшотами и макросами в духе SD-серии.", "Two touch screens, snapshots and macros in the SD spirit."),
                                      LText("Встроенные входы-выходы; расширение картами DMI (MADI, Dante и др.) и стейджбоксами DiGiCo.",
                                            "Built-in I/O; expansion with DMI cards (MADI, Dante and more) and DiGiCo stage boxes."),
                                      LText("Офлайн-софт для подготовки шоу и приложение для iPad.", "Offline software for show prep and an iPad app.")]),
                            .tip(LText("Сессии S-серии и SD-серии не всегда переносятся напрямую — проверьте совместимость версий.",
                                       "S-series and SD-series sessions do not always transfer directly — check version compatibility.")),
                            onlineNote,
                            manual("DiGiCo", "https://www.digico.biz"),
                        ]),
        HandbookArticle("rolandM5000", .consoles, title: LText("Roland M-5000", "Roland M-5000"),
                        subtitle: LText("Платформа O.H.R.C.A, стейджбоксы REAC", "O.H.R.C.A platform, REAC stage boxes"),
                        tags: ["roland", "роланд", "m-5000", "m5000", "m-5000c", "reac", "ohrca", "v-mixer"],
                        blocks: [
                            .bullets([LText("Гибкая архитектура O.H.R.C.A: число шин и каналов настраивается под задачу.", "Flexible O.H.R.C.A architecture: bus and channel counts are configured per job."),
                                      LText("Стейджбоксы по REAC (например, S-2416, S-1608), расширение картами (Dante, MADI и др.).",
                                            "REAC stage boxes (e.g. S-2416, S-1608), expansion cards (Dante, MADI and more)."),
                                      LText("M-5000 RCS — офлайн-редактор и удалённое управление.", "M-5000 RCS — offline editor and remote control.")]),
                            onlineNote,
                            manual("Roland", "https://www.roland.com"),
                        ]),
        HandbookArticle("consoleCommon", .consoles, title: LText("Любой цифровой пульт: чек-лист", "Any digital console: checklist"),
                        subtitle: LText("Что сделать на незнакомом пульте за 15 минут", "What to do on an unfamiliar console in 15 minutes"),
                        tags: ["checklist", "чек-лист", "незнакомый пульт", "festival", "фестиваль", "guest", "приглашённый"],
                        blocks: [
                            .steps([LText("Сохраните текущее шоу (сцену) владельца под отдельным именем.", "Save the owner's current show (scene) under a separate name."),
                                    LText("Найдите: роутинг входов, предусилители (где гейн и фантом), главный выход, посылы на мониторы.",
                                          "Find: input routing, preamps (gain and phantom), main output, monitor sends."),
                                    LText("Проверьте частоту дискретизации и синхронизацию (кто master clock).", "Check the sample rate and clock (who is master)."),
                                    LText("Найдите кнопки мьюта всего (Mute All / Mute Groups) и Talkback.", "Find mute-all (mute groups) and talkback."),
                                    LText("Настройте свой слой фейдеров: вокалы, группы/DCA, эффекты.", "Build your own fader layer: vocals, groups/DCAs, effects."),
                                    LText("Включите пользовательские права / блокировки, если пульт общий.", "Use user rights / locks if the console is shared.")]),
                        ]),
    ]
}
