import Foundation

/// Content of the handbook (written for SSMT; manufacturers' manuals are linked, not copied).
public enum HandbookContent {}

private typealias P = ConnectorDiagram.Pin

extension HandbookContent {
    static let pinouts: [HandbookArticle] = [
        HandbookArticle("xlr3", .pinouts, title: LText("XLR-3 (микрофон, линия)", "XLR-3 (mic, line)"),
                        subtitle: LText("Симметричный аналоговый сигнал, AES3", "Balanced analogue, AES3"),
                        tags: ["xlr", "canon", "кэнон", "микрофонный", "balanced", "симметричный", "aes"],
                        blocks: [
                            .connector(ConnectorDiagram(shape: .round, pins: [P("1", 0.68, 0.32), P("2", 0.32, 0.32), P("3", 0.5, 0.72)],
                                                        caption: LText("Мама (female) спереди или папа со стороны пайки; номера выбиты на самом разъёме", "Female front or male solder side; numbers are moulded on the connector"))),
                            .table(header: [LText("Контакт", "Pin"), LText("Сигнал", "Signal")],
                                   rows: [[LText("1"), LText("Экран (земля)", "Shield (ground)")],
                                          [LText("2"), LText("«Горячий» (+)", "Hot (+)")],
                                          [LText("3"), LText("«Холодный» (−)", "Cold (−)")],
                                          [LText("Корпус", "Shell"), LText("Обычно не соединён или через конденсатор", "Usually open or via a capacitor")]]),
                            .bullets([LText("Стандарт AES14 / IEC 60268-12: контакт 2 — «горячий».", "AES14 / IEC 60268-12: pin 2 hot."),
                                      LText("Мама (female) — на выходе сигнала, папа (male) — на входе: «сигнал течёт от мамы к папе».",
                                            "Female sends, male receives: signal flows from female to male."),
                                      LText("Тот же разъём для AES/EBU (цифра) — но кабель должен быть 110 Ом.", "The same connector carries AES/EBU digital — but use 110 Ω cable.")]),
                            .warning(LText("Перепутанные 2 и 3 дают переворот полярности — при сложении с другими микрофонами пропадает низ.",
                                           "Swapped 2 and 3 invert polarity — summed with other mics the low end disappears.")),
                        ]),
        HandbookArticle("trs", .pinouts, title: LText("Jack 6,3 мм TRS (стерео / симметричный)", "¼\" TRS jack (stereo / balanced)"),
                        subtitle: LText("Tip-Ring-Sleeve", "Tip-Ring-Sleeve"),
                        tags: ["jack", "джек", "trs", "6.3", "1/4", "stereo", "стерео", "balanced", "наушники"],
                        blocks: [
                            .connector(ConnectorDiagram(shape: .jack, pins: [P("T", 0.12, 0.5), P("R", 0.38, 0.5), P("S", 0.75, 0.5)],
                                                        caption: LText("Кончик · кольцо · гильза", "Tip · ring · sleeve"))),
                            .table(header: [LText("Контакт", "Contact"), LText("Симметричный", "Balanced"), LText("Стерео / наушники", "Stereo / headphones")],
                                   rows: [[LText("Tip"), LText("+ (горячий)", "+ (hot)"), LText("Левый", "Left")],
                                          [LText("Ring"), LText("− (холодный)", "− (cold)"), LText("Правый", "Right")],
                                          [LText("Sleeve"), LText("Экран", "Shield"), LText("Общий", "Common")]]),
                            .tip(LText("XLR ↔ TRS симметрично: 2→Tip, 3→Ring, 1→Sleeve.", "XLR ↔ TRS balanced: 2→Tip, 3→Ring, 1→Sleeve.")),
                        ]),
        HandbookArticle("ts", .pinouts, title: LText("Jack 6,3 мм TS (моно, несимметричный)", "¼\" TS jack (mono, unbalanced)"),
                        subtitle: LText("Гитара, клавиши, бытовая линия", "Guitar, keys, consumer line"),
                        tags: ["jack", "джек", "ts", "mono", "моно", "unbalanced", "гитарный", "instrument"],
                        blocks: [
                            .connector(ConnectorDiagram(shape: .jack, pins: [P("T", 0.12, 0.5), P("S", 0.6, 0.5)],
                                                        caption: LText("Кончик · гильза", "Tip · sleeve"))),
                            .table(header: [LText("Контакт", "Contact"), LText("Сигнал", "Signal")],
                                   rows: [[LText("Tip"), LText("Сигнал", "Signal")], [LText("Sleeve"), LText("Земля / экран", "Ground / shield")]]),
                            .bullets([LText("XLR → TS (несимметрично): 2→Tip, 3 и 1→Sleeve (на выходе с трансформатором — 3 можно оставить свободным).",
                                            "XLR → TS (unbalanced): 2→Tip, 3 and 1→Sleeve (leave 3 open on transformer outputs)."),
                                      LText("Гитарный кабель длиннее 6–8 м заметно срезает верх: используйте DI.", "Guitar cables over 6–8 m dull the top: use a DI.")]),
                        ]),
        HandbookArticle("insert", .pinouts, title: LText("Insert (разрыв) TRS", "Insert TRS"),
                        subtitle: LText("Посыл и возврат в одном джеке", "Send and return on one jack"),
                        tags: ["insert", "инсерт", "разрыв", "send", "return", "Y-cable", "игрек"],
                        blocks: [
                            .table(header: [LText("Контакт", "Contact"), LText("Обычно", "Common")],
                                   rows: [[LText("Tip"), LText("Посыл (send) из пульта", "Send from console")],
                                          [LText("Ring"), LText("Возврат (return) в пульт", "Return to console")],
                                          [LText("Sleeve"), LText("Земля", "Ground")]]),
                            .warning(LText("Некоторые производители делают наоборот (Tip — возврат). Проверьте в руководстве пульта; если звук пропал при подключении — поменяйте местами.",
                                           "Some makers swap them (tip = return). Check the console manual; if the sound disappears when patched, swap.")),
                            .tip(LText("Игрек-кабель: TRS → два TS (посыл и возврат).", "Y-cable: TRS → two TS (send and return).")),
                        ]),
        HandbookArticle("minijack", .pinouts, title: LText("Mini-jack 3,5 мм", "3.5 mm mini-jack"),
                        subtitle: LText("Телефон, ноутбук, наушники, TRRS", "Phone, laptop, headphones, TRRS"),
                        tags: ["mini jack", "миниджек", "3.5", "trrs", "aux", "телефон", "ноутбук"],
                        blocks: [
                            .table(header: [LText("Контакт", "Contact"), LText("TRS стерео", "TRS stereo"), LText("TRRS (CTIA, гарнитура)", "TRRS (CTIA headset)")],
                                   rows: [[LText("Tip"), LText("Левый", "Left"), LText("Левый", "Left")],
                                          [LText("Ring 1"), LText("Правый", "Right"), LText("Правый", "Right")],
                                          [LText("Ring 2"), LText("—"), LText("Земля", "Ground")],
                                          [LText("Sleeve"), LText("Земля", "Ground"), LText("Микрофон", "Microphone")]]),
                            .tip(LText("С телефона на пульт: mini-jack → 2 × XLR через DI-бокс (стерео DI) — без гула и с правильным уровнем.",
                                       "Phone to console: mini-jack → stereo DI → 2 × XLR — no hum and the right level.")),
                        ]),
        HandbookArticle("rca", .pinouts, title: LText("RCA (тюльпан)", "RCA (phono)"),
                        subtitle: LText("Бытовая линия, S/PDIF коаксиальный", "Consumer line, coaxial S/PDIF"),
                        tags: ["rca", "тюльпан", "cinch", "phono", "spdif", "dj"],
                        blocks: [
                            .table(header: [LText("Контакт", "Contact"), LText("Сигнал", "Signal")],
                                   rows: [[LText("Центр", "Centre pin"), LText("Сигнал", "Signal")], [LText("Кольцо", "Ring"), LText("Земля", "Ground")]]),
                            .bullets([LText("Уровень −10 dBV, несимметричный: короткие кабели, лучше через DI.", "−10 dBV unbalanced: keep cables short, use a DI."),
                                      LText("Цвета: красный — правый, белый/чёрный — левый, жёлтый — видео / S/PDIF.", "Colours: red right, white/black left, yellow video / S/PDIF.")]),
                        ]),
        HandbookArticle("speakon", .pinouts, title: LText("Speakon NL2 / NL4 / NL8", "Speakon NL2 / NL4 / NL8"),
                        subtitle: LText("Акустический разъём", "Loudspeaker connector"),
                        tags: ["speakon", "спикон", "nl4", "nl2", "nl8", "акустический", "колонка", "biamp", "биамп"],
                        blocks: [
                            .connector(ConnectorDiagram(shape: .round, pins: [P("1+", 0.32, 0.3), P("1−", 0.68, 0.3), P("2+", 0.32, 0.7), P("2−", 0.68, 0.7)],
                                                        caption: LText("NL4: четыре контакта, две пары", "NL4: four contacts, two pairs"))),
                            .table(header: [LText("Контакт", "Contact"), LText("Пассив (full-range)", "Passive (full range)"), LText("Биамп / два канала", "Bi-amp / two channels")],
                                   rows: [[LText("1+"), LText("+ колонки", "Speaker +"), LText("НЧ + (канал A)", "LF + (channel A)")],
                                          [LText("1−"), LText("− колонки", "Speaker −"), LText("НЧ −", "LF −")],
                                          [LText("2+"), LText("—"), LText("ВЧ + (канал B)", "HF + (channel B)")],
                                          [LText("2−"), LText("—"), LText("ВЧ −", "HF −")]]),
                            .bullets([LText("Стандарт де-факто: пассивные колонки и сабы — на 1+/1−. Многие колонки пробрасывают 2± на второй разъём.",
                                            "De facto: passive tops and subs on 1+/1−. Many boxes link 2± through to the second socket."),
                                      LText("NL8 — четыре пары (2+ … 4−) для многополосных систем.", "NL8 — four pairs for multi-way systems."),
                                      LText("NL2 подходит к гнезду NL4 и занимает только 1±.", "NL2 fits an NL4 socket and uses 1± only.")]),
                            .warning(LText("Не подключайте Speakon к выходу усилителя «на горячую» с громким сигналом — дуга портит контакты; сначала мьют.",
                                           "Do not plug Speakon into a live amp output with loud signal — arcing damages contacts; mute first.")),
                        ]),
        HandbookArticle("powercon", .pinouts, title: LText("powerCON / TRUE1 и сетевые разъёмы", "powerCON / TRUE1 and mains"),
                        subtitle: LText("Питание активных колонок", "Powering active speakers"),
                        tags: ["powercon", "пауэркон", "true1", "220", "mains", "питание", "iec", "schuko"],
                        blocks: [
                            .table(header: [LText("Разъём", "Connector"), LText("Где", "Where"), LText("Особенность", "Note")],
                                   rows: [[LText("powerCON синий", "powerCON blue"), LText("Вход питания", "Power in"), LText("Нельзя разрывать под нагрузкой", "Do not break under load")],
                                          [LText("powerCON серый", "powerCON grey"), LText("Выход (проброс)", "Power out (link)"), LText("Нельзя разрывать под нагрузкой", "Do not break under load")],
                                          [LText("powerCON TRUE1", "powerCON TRUE1"), LText("Вход и выход", "In and out"), LText("Можно разрывать под нагрузкой, IP65", "Breakable under load, IP65")],
                                          [LText("IEC C13/C14", "IEC C13/C14"), LText("Приборный", "Appliance"), LText("До 10 А", "Up to 10 A")]]),
                            .warning(LText("Суммарный ток проброса по цепочке ограничен (обычно 16 А на разъём и автомат линии) — считайте ток всех колонок.",
                                           "Daisy-chained current is limited (typically 16 A per connector and the line breaker) — add up all boxes.")),
                        ]),
        HandbookArticle("rj45", .pinouts, title: LText("RJ45 / etherCON (Ethernet, Dante, AES50)", "RJ45 / etherCON (Ethernet, Dante, AES50)"),
                        subtitle: LText("T568A и T568B", "T568A and T568B"),
                        tags: ["rj45", "ethercon", "эзеркон", "ethernet", "dante", "aes50", "cat5", "cat6", "витая пара", "t568b"],
                        blocks: [
                            .table(header: [LText("Контакт", "Pin"), LText("T568B (чаще)", "T568B (common)"), LText("T568A")],
                                   rows: [[LText("1"), LText("бело-оранжевый", "white-orange"), LText("бело-зелёный", "white-green")],
                                          [LText("2"), LText("оранжевый", "orange"), LText("зелёный", "green")],
                                          [LText("3"), LText("бело-зелёный", "white-green"), LText("бело-оранжевый", "white-orange")],
                                          [LText("4"), LText("синий", "blue"), LText("синий", "blue")],
                                          [LText("5"), LText("бело-синий", "white-blue"), LText("бело-синий", "white-blue")],
                                          [LText("6"), LText("зелёный", "green"), LText("оранжевый", "orange")],
                                          [LText("7"), LText("бело-коричневый", "white-brown"), LText("бело-коричневый", "white-brown")],
                                          [LText("8"), LText("коричневый", "brown"), LText("коричневый", "brown")]]),
                            .bullets([LText("Прямой кабель: обе стороны одинаково (B–B). Кроссовер: A–B — современным устройствам не нужен.",
                                            "Straight cable: same both ends (B–B). Crossover A–B is not needed by modern gear."),
                                      LText("AES50 (Behringer/Midas): экранированный Cat5e, экран соединён на обоих концах, до 100 м.",
                                            "AES50 (Behringer/Midas): shielded Cat5e, shield bonded at both ends, up to 100 m."),
                                      LText("Dante: Cat5e/Cat6, гигабитные свитчи, до 100 м сегмент.", "Dante: Cat5e/Cat6, gigabit switches, 100 m per segment.")]),
                        ]),
        HandbookArticle("dmx", .pinouts, title: LText("DMX512 (XLR-5 и XLR-3)", "DMX512 (XLR-5 and XLR-3)"),
                        subtitle: LText("Управление светом", "Lighting control"),
                        tags: ["dmx", "дмх", "свет", "light", "xlr5", "терминатор", "terminator"],
                        blocks: [
                            .table(header: [LText("Контакт", "Pin"), LText("Сигнал", "Signal")],
                                   rows: [[LText("1"), LText("Общий (экран)", "Common (shield)")],
                                          [LText("2"), LText("Data −")], [LText("3"), LText("Data +")],
                                          [LText("4, 5"), LText("Резерв (не использовать)", "Spare (do not use)")]]),
                            .bullets([LText("Кабель — 110–120 Ом (не микрофонный!), в конце линии — терминатор 120 Ом между 2 и 3.",
                                            "Use 110–120 Ω cable (not mic cable!), end the line with a 120 Ω terminator across 2 and 3."),
                                      LText("До 32 устройств на линию без сплиттера.", "Up to 32 devices per line without a splitter.")]),
                        ]),
        HandbookArticle("midi", .pinouts, title: LText("MIDI DIN-5", "MIDI DIN-5"),
                        subtitle: LText("Синтезаторы, контроллеры, MSC", "Synths, controllers, MSC"),
                        tags: ["midi", "миди", "din", "msc", "show control"],
                        blocks: [
                            .connector(ConnectorDiagram(shape: .round, pins: [P("1", 0.2, 0.42), P("4", 0.3, 0.68), P("2", 0.5, 0.78), P("5", 0.7, 0.68), P("3", 0.8, 0.42)],
                                                        caption: LText("Гнездо, вид спереди", "Socket, front view"))),
                            .table(header: [LText("Контакт", "Pin"), LText("Сигнал", "Signal")],
                                   rows: [[LText("4"), LText("Ток (+5 В через резистор)", "Current source (+5 V via resistor)")],
                                          [LText("5"), LText("Данные", "Data")], [LText("2"), LText("Экран", "Shield")],
                                          [LText("1, 3"), LText("Не используются", "Not used")]]),
                            .tip(LText("Длина кабеля — до 15 м. Дальше — MIDI по сети (rtpMIDI) или удлинители.", "Cable up to 15 m. Beyond that use network MIDI (rtpMIDI) or extenders.")),
                        ]),
        HandbookArticle("socapex", .pinouts, title: LText("Socapex 19-pin", "Socapex 19-pin"),
                        subtitle: LText("Шесть линий питания в одном кабеле", "Six power circuits in one cable"),
                        tags: ["socapex", "сокапекс", "19 pin", "multicore", "мульти", "питание"],
                        blocks: [
                            .table(header: [LText("Линия", "Circuit"), LText("Фаза (L)", "Live"), LText("Ноль (N)", "Neutral")],
                                   rows: [[LText("1"), LText("1"), LText("2")], [LText("2"), LText("3"), LText("4")], [LText("3"), LText("5"), LText("6")],
                                          [LText("4"), LText("7"), LText("8")], [LText("5"), LText("9"), LText("10")], [LText("6"), LText("11"), LText("12")],
                                          [LText("Земля", "Earth"), LText("13–18"), LText("")]]),
                            .warning(LText("Раскладка по линиям у разных производителей кабелей может отличаться — проверяйте тестером перед включением.",
                                           "Circuit layout may differ between cable makers — check with a tester before powering up.")),
                        ]),
        HandbookArticle("bnc", .pinouts, title: LText("BNC (word clock, MADI, видео)", "BNC (word clock, MADI, video)"),
                        subtitle: LText("75 Ом коаксиал", "75 Ω coax"),
                        tags: ["bnc", "word clock", "вордклок", "madi", "мади", "coax", "коаксиал", "синхронизация"],
                        blocks: [
                            .bullets([LText("Word clock: 75 Ом кабель, в конце цепочки — терминатор 75 Ом (если у устройства нет встроенного).",
                                            "Word clock: 75 Ω cable, 75 Ω terminator at the end of the chain (unless built in)."),
                                      LText("Тактовый генератор (master) в системе — один; остальные — slave.", "One clock master per system; the rest are slaves."),
                                      LText("MADI по коаксиалу — до ~100 м; по оптике — до 2 км.", "MADI over coax up to ~100 m; over fibre up to 2 km.")]),
                        ]),
        HandbookArticle("di", .pinouts, title: LText("DI-бокс и переходники", "DI box and adapters"),
                        subtitle: LText("Как правильно перейти с несимметрии на симметрию", "Going from unbalanced to balanced"),
                        tags: ["di", "ди бокс", "di-box", "ground lift", "переходник", "adapter", "гул", "hum"],
                        blocks: [
                            .bullets([LText("Пассивный DI — для активных источников (клавиши, плеер, бас с активной электроникой).",
                                            "Passive DI for active sources (keys, playback, active bass)."),
                                      LText("Активный DI — для пассивных звукоснимателей (акустика, пассивный бас): нужен фантом +48 В или батарейка.",
                                            "Active DI for passive pickups (acoustic, passive bass): needs +48 V phantom or a battery."),
                                      LText("Ground lift разрывает контакт 1 на выходе XLR — снимает фон из-за земляной петли.",
                                            "Ground lift opens pin 1 on the XLR output — cures ground-loop hum."),
                                      LText("PAD −20 дБ — для линейного и колоночного уровня.", "−20 dB PAD for line and speaker level.")]),
                            .warning(LText("Никогда не подавайте выход усилителя мощности в DI без делителя, рассчитанного на это (speaker-level DI).",
                                           "Never feed a power amp output into a DI unless it is rated for speaker level.")),
                        ]),
    ]
}
